# Generated by Django 4.1.1 on 2022-12-02 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0001_InitialParkingModels'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='park',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
