# Generated by Django 4.1.1 on 2022-12-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0002_park_latitude_park_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='webAddress',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
