# Generated by Django 4.1.1 on 2022-12-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0003_alter_park_address_alter_park_webaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='description',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
