# Generated by Django 4.1.1 on 2022-12-02 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0004_alter_park_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='webAddress',
            new_name='web_address',
        ),
        migrations.AlterField(
            model_name='park',
            name='description',
            field=models.CharField(default=None, max_length=128, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
