# Generated by Django 4.1.1 on 2023-01-03 09:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0005_rename_webaddress_park_web_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkinginfo',
            old_name='checkout_time',
            new_name='checkout_time_utc',
        ),
        migrations.RemoveField(
            model_name='parkinginfo',
            name='entry_time',
        ),
        migrations.AddField(
            model_name='parkinginfo',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('All', 'All'), ('Wkd', 'Weekend'), ('Mon', 'Monday'), ('Tue', 'Thuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='All', max_length=3)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_time_in_minutes', models.IntegerField(default=0)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingApp.park')),
            ],
            options={
                'unique_together': {('id', 'day_of_week')},
            },
        ),
        migrations.AddField(
            model_name='parkinginfo',
            name='entry_time_utc',
            field=models.DateTimeField(),
        ),
    ]
