# Generated by Django 4.1.1 on 2023-01-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0006_price_squashed_0010_alter_parkinginfo_entry_time_utc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('park', 'day_of_week'), name='unique week day'),
        ),
    ]
