# Generated by Django 4.1.1 on 2023-01-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0011_alter_price_unique_together_price_unique week day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinginfo',
            name='park',
            field=models.ForeignKey(on_delete=models.SET(0), to='parkingApp.park'),
        ),
        migrations.AlterField(
            model_name='price',
            name='day_of_week',
            field=models.CharField(choices=[('All', 'All'), ('Wkd', 'Weekend'), ('Mon', 'Monday'), ('Tue', 'Thuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3),
        ),
        migrations.AlterField(
            model_name='price',
            name='free_time_in_minutes',
            field=models.IntegerField(),
        ),
    ]
