# Generated by Django 4.1.1 on 2023-05-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingApp', '0014_parkinginfo_unregistred_car_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationcode',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
